---
- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: true

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
    state: present
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Install Docker
  apt:
    name: docker-ce
    state: present
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Install Docker Compose via pip
  pip:
    name: docker-compose
    state: present
  when: docker_installed.rc != 0

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
