---
- name: Verificar se o Docker está instalado
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Atualizar cache do apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Instalar dependências do Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Adicionar chave GPG oficial do Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Adicionar repositório do Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Instalar Docker Engine e plugins
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_os_family == "Debian" and docker_installed.rc != 0

- name: Garantir que o serviço Docker está ativo e habilitado
  service:
    name: docker
    state: started
    enabled: yes
